// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIgEIE6u8PWJrkQWr1z62Id6SvBLXgnWA',
    appId: '1:616628955250:web:652692e126a8e9cc22faeb',
    messagingSenderId: '616628955250',
    projectId: 'vults-app-dev',
    authDomain: 'vults-app-dev.firebaseapp.com',
    storageBucket: 'vults-app-dev.firebasestorage.app',
    measurementId: 'G-BZS3888190',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOwcNMiYwPRDZNDFJCI7ox0zXDMEGCGnY',
    appId: '1:616628955250:android:6d80eb3aa65e7cd822faeb',
    messagingSenderId: '616628955250',
    projectId: 'vults-app-dev',
    storageBucket: 'vults-app-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYpaNMwFqqcqom9PLyHkavgq_y7COJMgI',
    appId: '1:616628955250:ios:91e56e533f88069c22faeb',
    messagingSenderId: '616628955250',
    projectId: 'vults-app-dev',
    storageBucket: 'vults-app-dev.firebasestorage.app',
    iosBundleId: 'com.example.vults',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYpaNMwFqqcqom9PLyHkavgq_y7COJMgI',
    appId: '1:616628955250:ios:91e56e533f88069c22faeb',
    messagingSenderId: '616628955250',
    projectId: 'vults-app-dev',
    storageBucket: 'vults-app-dev.firebasestorage.app',
    iosBundleId: 'com.example.vults',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIgEIE6u8PWJrkQWr1z62Id6SvBLXgnWA',
    appId: '1:616628955250:web:6df5dde9ca9285d622faeb',
    messagingSenderId: '616628955250',
    projectId: 'vults-app-dev',
    authDomain: 'vults-app-dev.firebaseapp.com',
    storageBucket: 'vults-app-dev.firebasestorage.app',
    measurementId: 'G-3N37END00S',
  );

}