// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxXiMXIKg3crx8U1svhikr9p-dhnW-EQY',
    appId: '1:375939365635:web:bcaafb2ad65d327d3c4736',
    messagingSenderId: '375939365635',
    projectId: 'volts-app-70252',
    authDomain: 'volts-app-70252.firebaseapp.com',
    storageBucket: 'volts-app-70252.firebasestorage.app',
    measurementId: 'G-0SD6B2PX3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa-PK9dKHnwdzfO9lswENn6X_s6MXi3Hk',
    appId: '1:375939365635:android:d55ab11ae2ad86bb3c4736',
    messagingSenderId: '375939365635',
    projectId: 'volts-app-70252',
    storageBucket: 'volts-app-70252.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtLFGS8EpxmTQrjn1IMcm_GfaHUTKScNk',
    appId: '1:375939365635:ios:299d17e772b7d6d53c4736',
    messagingSenderId: '375939365635',
    projectId: 'volts-app-70252',
    storageBucket: 'volts-app-70252.firebasestorage.app',
    iosBundleId: 'com.example.vults',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtLFGS8EpxmTQrjn1IMcm_GfaHUTKScNk',
    appId: '1:375939365635:ios:299d17e772b7d6d53c4736',
    messagingSenderId: '375939365635',
    projectId: 'volts-app-70252',
    storageBucket: 'volts-app-70252.firebasestorage.app',
    iosBundleId: 'com.example.vults',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxXiMXIKg3crx8U1svhikr9p-dhnW-EQY',
    appId: '1:375939365635:web:23a959f4d6f22ca53c4736',
    messagingSenderId: '375939365635',
    projectId: 'volts-app-70252',
    authDomain: 'volts-app-70252.firebaseapp.com',
    storageBucket: 'volts-app-70252.firebasestorage.app',
    measurementId: 'G-9LZS3Y3655',
  );
}
